server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:${DB_NAME}://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_SCHEMA}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8InnoDBBialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui/index.html

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: us-east-1
    s3:
      bucket:
        name: ${AWS_S3_BUCKET_NAME}

logging:
  level:
    org.springframework: DEBUG

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_TIME}

client:
  appUrl: http://localhost:4200